// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/crawl": {
            "post": {
                "description": "Submits a URL to be crawled asynchronously using the background worker queue. Requires Redis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawl"
                ],
                "summary": "Enqueue a URL for asynchronous crawling",
                "parameters": [
                    {
                        "description": "JSON request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CrawlRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/handlers.CrawlResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/crawl/{id}": {
            "get": {
                "description": "Retrieves the current status and result of a previously enqueued crawl task by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawl"
                ],
                "summary": "Get the status of an asynchronous crawl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The crawl task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The task status and result payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/scrape": {
            "get": {
                "description": "Scrapes a given URL and returns its markdown content, metadata, and optionally captures a screenshot or extracts images if enabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "Scrape a webpage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The URL to scrape",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Scraping mode: smart, static, dynamic",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Deprecated: use mode=dynamic instead",
                        "name": "render",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Capture full-page screenshot (requires mode=dynamic or smart)",
                        "name": "screenshot",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Extract images as base64 blobs",
                        "name": "images",
                        "in": "query"
                    },
                    {
                        "description": "JSON request body (alternative to query params)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ScrapeResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Scrapes a given URL and returns its markdown content, metadata, and optionally captures a screenshot or extracts images if enabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "Scrape a webpage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The URL to scrape",
                        "name": "url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Scraping mode: smart, static, dynamic",
                        "name": "mode",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Deprecated: use mode=dynamic instead",
                        "name": "render",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Capture full-page screenshot (requires mode=dynamic or smart)",
                        "name": "screenshot",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Extract images as base64 blobs",
                        "name": "images",
                        "in": "query"
                    },
                    {
                        "description": "JSON request body (alternative to query params)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ScrapeResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Searches the web using the configured search provider (Brave Search) and returns a list of matching results.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search the web",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The search query",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Alias for query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "description": "JSON request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Searches the web using the configured search provider (Brave Search) and returns a list of matching results.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search the web",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The search query",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Alias for query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "description": "JSON request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ImageData": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "string"
                },
                "blob": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "domain.ScrapeResult": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ImageData"
                    }
                },
                "markdown": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "screenshot": {
                    "description": "Image fields (omitted when not requested)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ScreenshotData"
                        }
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.ScreenshotData": {
            "type": "object",
            "properties": {
                "blob": {
                    "type": "string"
                },
                "captured_at": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "full_page": {
                    "type": "boolean"
                },
                "height": {
                    "type": "integer"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "handlers.CrawlRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "images": {
                    "type": "boolean"
                },
                "render": {
                    "type": "boolean"
                },
                "screenshot": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.CrawlResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "boolean"
                },
                "render": {
                    "type": "boolean"
                },
                "screenshot": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.ScrapeRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "images": {
                    "type": "boolean"
                },
                "mode": {
                    "description": "\"smart\", \"static\", \"dynamic\"",
                    "type": "string"
                },
                "render": {
                    "description": "Deprecated: usage ignores Mode if true",
                    "type": "boolean"
                },
                "screenshot": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.SearchRequest": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "excludeDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "includeDomains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "maxAge": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "requiredText": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.SearchResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "nextOffset": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.Result"
                    }
                }
            }
        },
        "search.Result": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "relevance": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Cinder API",
	Description:      "Web scraping, crawling, and AI data extraction API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
